### PR TITLE
Add alpine variant

### PR DESCRIPTION
**Pull request by ncopa**
I added an additional image for now, but it might make more sense to replace the existing?

``` console
$ docker images | grep irssi
irssi       0.8.17-alpine           60bb4ee71d57        About a minute ago   61.66 MB
irssi       0.8.17                  1c96cb99f9b7        5 weeks ago          261.1 MB
```

### CODE REVIEW

**Comment by ncopa** [comment]
I replaced the existing. It probably don't make sense to maintain both.

**Comment by jessfraz** [comment]
Cool!, ping @tianon as well but i like it!

**Comment by tianon** [comment]
I'm definitely +1, but I'm not sure I'm a fan of outright replacement, especially given that extra Perl modules for additional scripts are likely easier to find/install in Debian (and the existing userbase may already have `Dockerfile`s from this one which would break if we just pull the rug like this).

**Comment by jessfraz** [comment]
ok maybe lets go with an additional tag so sorry

**Comment by jessfraz** [comment]
LGTM after a rebase so sorry

**Comment by tianon** [comment]
I can carry this from here if you'd like :+1:

**Pull request closed without merging**
