### PR TITLE
RFC: add otr variant

### PR DESCRIPTION
**Pull request by jessfraz**
This is a proposal to add an OTR variant to the irssi official image. 

I didn't update the stackbrew script because idk if we even want this or in this heirarchy.

ping @tianon @ncopa :innocent:

### CODE REVIEW

**Comment by ncopa** [comment]
You could `apk add libotr-dev` instead of building it from source.

**Comment by tianon** [comment]
This is definitely interesting (and I can imagine myself using it), but my question would be where we draw the line -- if we've got a custom variant for this plugin/addon, why not others too?  From the official-images side, my question would be whether this is officially recommended by upstream, and I think the fact that it's still a separate repo is probably the answer to that. :disappointed:

Does it require patching irssi in any way, or is it possible to do this today already with a `FROM irssi`?  (ie, could we document how users are expected to do this themselves instead?)

**Comment by jessfraz** [comment]
yes i was thinking the same, the problem is it needs the header files :(

On Mon, Apr 18, 2016 at 3:17 PM, Tianon Gravi notifications@github.com
wrote:

> This is definitely interesting (and I can imagine myself using it), but my
> question would be where we draw the line -- if we've got a custom variant
> for this plugin/addon, why not others too? From the official-images side,
> my question would be whether this is officially recommended by upstream,
> and I think the fact that it's still a separate repo is probably the answer
> to that. [image: :disappointed:]
> 
> Does it require patching irssi in any way, or is it possible to do this
> today already with a FROM irssi? (ie, could we document how users are
> expected to do this themselves instead?)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/jfrazelle/irssi/pull/9#issuecomment-211603965

## 

Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3

**Comment by tianon** [comment]
Hmm, how big are the header files, and is there a "make" target upstream to
install them to an appropriate location? :smile:

**Comment by jessfraz** [comment]
I'm kinda over it haha

On Mon, Apr 18, 2016 at 3:29 PM, Tianon Gravi notifications@github.com
wrote:

> Hmm, how big are the header files, and is there a "make" target upstream to
> install them to an appropriate location? :smile:
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/jfrazelle/irssi/pull/9#issuecomment-211607842

## 

Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3

**Comment by tianon** [comment]
Worth noting https://lists.cypherpunks.ca/pipermail/otr-dev/2016-April/002495.html :smile:

**Comment by tianon** [comment]
Just to help thread this back -- the upstream discussion has continued somewhat over in https://github.com/irssi/irssi/issues/196 and/or https://github.com/irssi/irssi/pull/589. :+1:

**Comment by tianon** [comment]
As of http://irssi.org/2019/02/11/irssi-1.2.0-released/ + https://github.com/jessfraz/irssi/commit/ec5a36f9e17511c0b9768719db0aeeef1715fe42, we're liiiiiiive!!!! :tada:

**Pull request closed without merging**
